### ISSUE TITLE
issue with taurus 4.0.3

### ISSUE THREAD

**Issue by hayg25** [MaxIV-KitsControls/app-maxiv-linacsynoptic#1]
taurus.qt.qtgui.panel import TaurusWidget 
--> TaurusWidget is not located there anymore 

should be --> from taurus.qt.qtgui.container import TaurusWidget

**Comment by johanfforsberg** [comment]
Thanks!

I suspect there will be some more Taurus 4 related issues, in that case perhaps we can collect them in this issue. I may not have time to look at this properly until we start migrating to Taurus 4, but PR:s would be very welcome! (Obviously we should take care to support both older and newer versions)

**Comment by ghost** [comment]
fixed with #4
